name: Auto-Build
on:
  push:
    branches: [ master ]

env:
    TVDB_API_KEY: ${{ secrets.TVDB_API_KEY }}
    TVDB_API_PIN: ${{ secrets.TVDB_API_PIN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: |
            6
            7
            8

      - name: Test
        run: dotnet test -c release
